<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->delete();
        $countries = [
            [
                "id" => 1,
                "code" => "AF",
                "name" => "Afghanistan",
                "phone_code" => 93,
                "currency_id" => 1,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 2,
                "code" => "AL",
                "name" => "Albania",
                "phone_code" => 355,
                "currency_id" => 2,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 3,
                "code" => "DZ",
                "name" => "Algeria",
                "phone_code" => 213,
                "currency_id" => 3,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 4,
                "code" => "AS",
                "name" => "American Samoa",
                "phone_code" => 1684,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 5,
                "code" => "AD",
                "name" => "Andorra",
                "phone_code" => 376,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 6,
                "code" => "AO",
                "name" => "Angola",
                "phone_code" => 244,
                "currency_id" => 6,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 7,
                "code" => "AI",
                "name" => "Anguilla",
                "phone_code" => 1264,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 8,
                "code" => "AQ",
                "name" => "Antarctica",
                "phone_code" => 0,
                "currency_id" => 4,
                "region_id" => 6,
                "subregion_id" => 1,
            ],
            [
                "id" => 9,
                "code" => "AG",
                "name" => "Antigua And Barbuda",
                "phone_code" => 1268,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 10,
                "code" => "AR",
                "name" => "Argentina",
                "phone_code" => 54,
                "currency_id" => 8,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 11,
                "code" => "AM",
                "name" => "Armenia",
                "phone_code" => 374,
                "currency_id" => 9,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 12,
                "code" => "AW",
                "name" => "Aruba",
                "phone_code" => 297,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 13,
                "code" => "AU",
                "name" => "Australia",
                "phone_code" => 61,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 17,
            ],
            [
                "id" => 14,
                "code" => "AT",
                "name" => "Austria",
                "phone_code" => 43,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 15,
                "code" => "AZ",
                "name" => "Azerbaijan",
                "phone_code" => 994,
                "currency_id" => 12,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 16,
                "code" => "BS",
                "name" => "Bahamas The",
                "phone_code" => 1242,
                "currency_id" => 13,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 17,
                "code" => "BH",
                "name" => "Bahrain",
                "phone_code" => 973,
                "currency_id" => 14,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 18,
                "code" => "BD",
                "name" => "Bangladesh",
                "phone_code" => 880,
                "currency_id" => 15,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 19,
                "code" => "BB",
                "name" => "Barbados",
                "phone_code" => 1246,
                "currency_id" => 16,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 20,
                "code" => "BY",
                "name" => "Belarus",
                "phone_code" => 375,
                "currency_id" => 17,
                "region_id" => 2,
                "subregion_id" => 7,
            ],
            [
                "id" => 21,
                "code" => "BE",
                "name" => "Belgium",
                "phone_code" => 32,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 22,
                "code" => "BZ",
                "name" => "Belize",
                "phone_code" => 501,
                "currency_id" => 18,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 23,
                "code" => "BJ",
                "name" => "Benin",
                "phone_code" => 229,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 24,
                "code" => "BM",
                "name" => "Bermuda",
                "phone_code" => 1441,
                "currency_id" => 20,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 25,
                "code" => "BT",
                "name" => "Bhutan",
                "phone_code" => 975,
                "currency_id" => 21,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 26,
                "code" => "BO",
                "name" => "Bolivia",
                "phone_code" => 591,
                "currency_id" => 22,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 27,
                "code" => "BA",
                "name" => "Bosnia and Herzegovina",
                "phone_code" => 387,
                "currency_id" => 23,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 28,
                "code" => "BW",
                "name" => "Botswana",
                "phone_code" => 267,
                "currency_id" => 24,
                "region_id" => 3,
                "subregion_id" => 15,
            ],
            [
                "id" => 29,
                "code" => "BV",
                "name" => "Bouvet Island",
                "phone_code" => 0,
                "currency_id" => 4,
                "region_id" => 6,
                "subregion_id" => 1,
            ],
            [
                "id" => 30,
                "code" => "BR",
                "name" => "Brazil",
                "phone_code" => 55,
                "currency_id" => 25,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 31,
                "code" => "IO",
                "name" => "British Indian Ocean Territory",
                "phone_code" => 246,
                "currency_id" => 4,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 32,
                "code" => "BN",
                "name" => "Brunei",
                "phone_code" => 673,
                "currency_id" => 26,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 33,
                "code" => "BG",
                "name" => "Bulgaria",
                "phone_code" => 359,
                "currency_id" => 27,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 34,
                "code" => "BF",
                "name" => "Burkina Faso",
                "phone_code" => 226,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 35,
                "code" => "BI",
                "name" => "Burundi",
                "phone_code" => 257,
                "currency_id" => 28,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 36,
                "code" => "KH",
                "name" => "Cambodia",
                "phone_code" => 855,
                "currency_id" => 29,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 37,
                "code" => "CM",
                "name" => "Cameroon",
                "phone_code" => 237,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 38,
                "code" => "CA",
                "name" => "Canada",
                "phone_code" => 1,
                "currency_id" => 31,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 39,
                "code" => "CV",
                "name" => "Cape Verde",
                "phone_code" => 238,
                "currency_id" => 32,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 40,
                "code" => "KY",
                "name" => "Cayman Islands",
                "phone_code" => 1345,
                "currency_id" => 33,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 41,
                "code" => "CF",
                "name" => "Central African Republic",
                "phone_code" => 236,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 42,
                "code" => "TD",
                "name" => "Chad",
                "phone_code" => 235,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 43,
                "code" => "CL",
                "name" => "Chile",
                "phone_code" => 56,
                "currency_id" => 34,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 44,
                "code" => "CN",
                "name" => "China",
                "phone_code" => 86,
                "currency_id" => 35,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 45,
                "code" => "CX",
                "name" => "Christmas Island",
                "phone_code" => 61,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 17,
            ],
            [
                "id" => 46,
                "code" => "CC",
                "name" => "Cocos (Keeling) Islands",
                "phone_code" => 672,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 17,
            ],
            [
                "id" => 47,
                "code" => "CO",
                "name" => "Colombia",
                "phone_code" => 57,
                "currency_id" => 36,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 48,
                "code" => "KM",
                "name" => "Comoros",
                "phone_code" => 269,
                "currency_id" => 37,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 49,
                "code" => "CG",
                "name" => "Congo",
                "phone_code" => 242,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 50,
                "code" => "CD",
                "name" => "Congo The Democratic Republic Of The",
                "phone_code" => 242,
                "currency_id" => 38,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 51,
                "code" => "CK",
                "name" => "Cook Islands",
                "phone_code" => 682,
                "currency_id" => 39,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 52,
                "code" => "CR",
                "name" => "Costa Rica",
                "phone_code" => 506,
                "currency_id" => 40,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 53,
                "code" => "CI",
                "name" => "Cote D Ivoire (Ivory Coast)",
                "phone_code" => 225,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 54,
                "code" => "HR",
                "name" => "Croatia (Hrvatska)",
                "phone_code" => 385,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 55,
                "code" => "CU",
                "name" => "Cuba",
                "phone_code" => 53,
                "currency_id" => 41,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 56,
                "code" => "CY",
                "name" => "Cyprus",
                "phone_code" => 357,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 57,
                "code" => "CZ",
                "name" => "Czech Republic",
                "phone_code" => 420,
                "currency_id" => 42,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 58,
                "code" => "DK",
                "name" => "Denmark",
                "phone_code" => 45,
                "currency_id" => 43,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 59,
                "code" => "DJ",
                "name" => "Djibouti",
                "phone_code" => 253,
                "currency_id" => 44,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 60,
                "code" => "DM",
                "name" => "Dominica",
                "phone_code" => 1767,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 61,
                "code" => "DO",
                "name" => "Dominican Republic",
                "phone_code" => 1809,
                "currency_id" => 45,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 62,
                "code" => "TP",
                "name" => "East Timor",
                "phone_code" => 670,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 63,
                "code" => "EC",
                "name" => "Ecuador",
                "phone_code" => 593,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 64,
                "code" => "EG",
                "name" => "Egypt",
                "phone_code" => 20,
                "currency_id" => 46,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 65,
                "code" => "SV",
                "name" => "El Salvador",
                "phone_code" => 503,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 66,
                "code" => "GQ",
                "name" => "Equatorial Guinea",
                "phone_code" => 240,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 67,
                "code" => "ER",
                "name" => "Eritrea",
                "phone_code" => 291,
                "currency_id" => 47,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 68,
                "code" => "EE",
                "name" => "Estonia",
                "phone_code" => 372,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 69,
                "code" => "ET",
                "name" => "Ethiopia",
                "phone_code" => 251,
                "currency_id" => 48,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 70,
                "code" => "XA",
                "name" => "External Territories of Australia",
                "phone_code" => 61,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 71,
                "code" => "FK",
                "name" => "Falkland Islands",
                "phone_code" => 500,
                "currency_id" => 49,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 72,
                "code" => "FO",
                "name" => "Faroe Islands",
                "phone_code" => 298,
                "currency_id" => 43,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 73,
                "code" => "FJ",
                "name" => "Fiji Islands",
                "phone_code" => 679,
                "currency_id" => 50,
                "region_id" => 4,
                "subregion_id" => 18,
            ],
            [
                "id" => 74,
                "code" => "FI",
                "name" => "Finland",
                "phone_code" => 358,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 75,
                "code" => "FR",
                "name" => "France",
                "phone_code" => 33,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 76,
                "code" => "GF",
                "name" => "French Guiana",
                "phone_code" => 594,
                "currency_id" => 5,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 77,
                "code" => "PF",
                "name" => "French Polynesia",
                "phone_code" => 689,
                "currency_id" => 51,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 78,
                "code" => "TF",
                "name" => "French Southern Territories",
                "phone_code" => 0,
                "currency_id" => 5,
                "region_id" => 6,
                "subregion_id" => 1,
            ],
            [
                "id" => 79,
                "code" => "GA",
                "name" => "Gabon",
                "phone_code" => 241,
                "currency_id" => 30,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 80,
                "code" => "GM",
                "name" => "Gambia The",
                "phone_code" => 220,
                "currency_id" => 52,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 81,
                "code" => "GE",
                "name" => "Georgia",
                "phone_code" => 995,
                "currency_id" => 53,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 82,
                "code" => "DE",
                "name" => "Germany",
                "phone_code" => 49,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 83,
                "code" => "GH",
                "name" => "Ghana",
                "phone_code" => 233,
                "currency_id" => 54,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 84,
                "code" => "GI",
                "name" => "Gibraltar",
                "phone_code" => 350,
                "currency_id" => 55,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 85,
                "code" => "GR",
                "name" => "Greece",
                "phone_code" => 30,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 86,
                "code" => "GL",
                "name" => "Greenland",
                "phone_code" => 299,
                "currency_id" => 43,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 87,
                "code" => "GD",
                "name" => "Grenada",
                "phone_code" => 1473,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 88,
                "code" => "GP",
                "name" => "Guadeloupe",
                "phone_code" => 590,
                "currency_id" => 5,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 89,
                "code" => "GU",
                "name" => "Guam",
                "phone_code" => 1671,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 90,
                "code" => "GT",
                "name" => "Guatemala",
                "phone_code" => 502,
                "currency_id" => 56,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 91,
                "code" => "XU",
                "name" => "Guernsey and Alderney",
                "phone_code" => 44,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 92,
                "code" => "GN",
                "name" => "Guinea",
                "phone_code" => 224,
                "currency_id" => 57,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 93,
                "code" => "GW",
                "name" => "Guinea-Bissau",
                "phone_code" => 245,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 94,
                "code" => "GY",
                "name" => "Guyana",
                "phone_code" => 592,
                "currency_id" => 58,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 95,
                "code" => "HT",
                "name" => "Haiti",
                "phone_code" => 509,
                "currency_id" => 59,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 96,
                "code" => "HM",
                "name" => "Heard and McDonald Islands",
                "phone_code" => 0,
                "currency_id" => 4,
                "region_id" => 6,
                "subregion_id" => 1,
            ],
            [
                "id" => 97,
                "code" => "HN",
                "name" => "Honduras",
                "phone_code" => 504,
                "currency_id" => 60,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 98,
                "code" => "HK",
                "name" => "Hong Kong S.A.R.",
                "phone_code" => 852,
                "currency_id" => 61,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 99,
                "code" => "HU",
                "name" => "Hungary",
                "phone_code" => 36,
                "currency_id" => 62,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 100,
                "code" => "IS",
                "name" => "Iceland",
                "phone_code" => 354,
                "currency_id" => 63,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 101,
                "code" => "IN",
                "name" => "India",
                "phone_code" => 91,
                "currency_id" => 64,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 102,
                "code" => "ID",
                "name" => "Indonesia",
                "phone_code" => 62,
                "currency_id" => 65,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 103,
                "code" => "IR",
                "name" => "Iran",
                "phone_code" => 98,
                "currency_id" => 66,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 104,
                "code" => "IQ",
                "name" => "Iraq",
                "phone_code" => 964,
                "currency_id" => 67,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 105,
                "code" => "IE",
                "name" => "Ireland",
                "phone_code" => 353,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 106,
                "code" => "IL",
                "name" => "Israel",
                "phone_code" => 972,
                "currency_id" => 68,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 107,
                "code" => "IT",
                "name" => "Italy",
                "phone_code" => 39,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 108,
                "code" => "JM",
                "name" => "Jamaica",
                "phone_code" => 1876,
                "currency_id" => 69,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 109,
                "code" => "JP",
                "name" => "Japan",
                "phone_code" => 81,
                "currency_id" => 70,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 110,
                "code" => "XJ",
                "name" => "Jersey",
                "phone_code" => 44,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 111,
                "code" => "JO",
                "name" => "Jordan",
                "phone_code" => 962,
                "currency_id" => 71,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 112,
                "code" => "KZ",
                "name" => "Kazakhstan",
                "phone_code" => 7,
                "currency_id" => 72,
                "region_id" => 1,
                "subregion_id" => 1,
            ],
            [
                "id" => 113,
                "code" => "KE",
                "name" => "Kenya",
                "phone_code" => 254,
                "currency_id" => 73,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 114,
                "code" => "KI",
                "name" => "Kiribati",
                "phone_code" => 686,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 115,
                "code" => "KP",
                "name" => "Korea North",
                "phone_code" => 850,
                "currency_id" => 74,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 116,
                "code" => "KR",
                "name" => "Korea South",
                "phone_code" => 82,
                "currency_id" => 75,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 117,
                "code" => "KW",
                "name" => "Kuwait",
                "phone_code" => 965,
                "currency_id" => 76,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 118,
                "code" => "KG",
                "name" => "Kyrgyzstan",
                "phone_code" => 996,
                "currency_id" => 77,
                "region_id" => 1,
                "subregion_id" => 1,
            ],
            [
                "id" => 119,
                "code" => "LA",
                "name" => "Laos",
                "phone_code" => 856,
                "currency_id" => 78,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 120,
                "code" => "LV",
                "name" => "Latvia",
                "phone_code" => 371,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 121,
                "code" => "LB",
                "name" => "Lebanon",
                "phone_code" => 961,
                "currency_id" => 79,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 122,
                "code" => "LS",
                "name" => "Lesotho",
                "phone_code" => 266,
                "currency_id" => 80,
                "region_id" => 3,
                "subregion_id" => 15,
            ],
            [
                "id" => 123,
                "code" => "LR",
                "name" => "Liberia",
                "phone_code" => 231,
                "currency_id" => 81,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 124,
                "code" => "LY",
                "name" => "Libya",
                "phone_code" => 218,
                "currency_id" => 82,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 125,
                "code" => "LI",
                "name" => "Liechtenstein",
                "phone_code" => 423,
                "currency_id" => 83,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 126,
                "code" => "LT",
                "name" => "Lithuania",
                "phone_code" => 370,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 127,
                "code" => "LU",
                "name" => "Luxembourg",
                "phone_code" => 352,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 128,
                "code" => "MO",
                "name" => "Macau S.A.R.",
                "phone_code" => 853,
                "currency_id" => 84,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 129,
                "code" => "MK",
                "name" => "Macedonia",
                "phone_code" => 389,
                "currency_id" => 85,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 130,
                "code" => "MG",
                "name" => "Madagascar",
                "phone_code" => 261,
                "currency_id" => 86,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 131,
                "code" => "MW",
                "name" => "Malawi",
                "phone_code" => 265,
                "currency_id" => 87,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 132,
                "code" => "MY",
                "name" => "Malaysia",
                "phone_code" => 60,
                "currency_id" => 88,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 133,
                "code" => "MV",
                "name" => "Maldives",
                "phone_code" => 960,
                "currency_id" => 89,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 134,
                "code" => "ML",
                "name" => "Mali",
                "phone_code" => 223,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 135,
                "code" => "MT",
                "name" => "Malta",
                "phone_code" => 356,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 136,
                "code" => "XM",
                "name" => "Man (Isle of)",
                "phone_code" => 44,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 137,
                "code" => "MH",
                "name" => "Marshall Islands",
                "phone_code" => 692,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 138,
                "code" => "MQ",
                "name" => "Martinique",
                "phone_code" => 596,
                "currency_id" => 5,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 139,
                "code" => "MR",
                "name" => "Mauritania",
                "phone_code" => 222,
                "currency_id" => 90,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 140,
                "code" => "MU",
                "name" => "Mauritius",
                "phone_code" => 230,
                "currency_id" => 91,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 141,
                "code" => "YT",
                "name" => "Mayotte",
                "phone_code" => 269,
                "currency_id" => 5,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 142,
                "code" => "MX",
                "name" => "Mexico",
                "phone_code" => 52,
                "currency_id" => 92,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 143,
                "code" => "FM",
                "name" => "Micronesia",
                "phone_code" => 691,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 144,
                "code" => "MD",
                "name" => "Moldova",
                "phone_code" => 373,
                "currency_id" => 93,
                "region_id" => 2,
                "subregion_id" => 7,
            ],
            [
                "id" => 145,
                "code" => "MC",
                "name" => "Monaco",
                "phone_code" => 377,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 146,
                "code" => "MN",
                "name" => "Mongolia",
                "phone_code" => 976,
                "currency_id" => 94,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 147,
                "code" => "MS",
                "name" => "Montserrat",
                "phone_code" => 1664,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 148,
                "code" => "MA",
                "name" => "Morocco",
                "phone_code" => 212,
                "currency_id" => 95,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 149,
                "code" => "MZ",
                "name" => "Mozambique",
                "phone_code" => 258,
                "currency_id" => 96,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 150,
                "code" => "MM",
                "name" => "Myanmar",
                "phone_code" => 95,
                "currency_id" => 97,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 151,
                "code" => "NA",
                "name" => "Namibia",
                "phone_code" => 264,
                "currency_id" => 98,
                "region_id" => 3,
                "subregion_id" => 15,
            ],
            [
                "id" => 152,
                "code" => "NR",
                "name" => "Nauru",
                "phone_code" => 674,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 153,
                "code" => "NP",
                "name" => "Nepal",
                "phone_code" => 977,
                "currency_id" => 99,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 154,
                "code" => "AN",
                "name" => "Netherlands Antilles",
                "phone_code" => 599,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 155,
                "code" => "NL",
                "name" => "Netherlands The",
                "phone_code" => 31,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 156,
                "code" => "NC",
                "name" => "New Caledonia",
                "phone_code" => 687,
                "currency_id" => 51,
                "region_id" => 4,
                "subregion_id" => 18,
            ],
            [
                "id" => 157,
                "code" => "NZ",
                "name" => "New Zealand",
                "phone_code" => 64,
                "currency_id" => 100,
                "region_id" => 4,
                "subregion_id" => 17,
            ],
            [
                "id" => 158,
                "code" => "NI",
                "name" => "Nicaragua",
                "phone_code" => 505,
                "currency_id" => 101,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 159,
                "code" => "NE",
                "name" => "Niger",
                "phone_code" => 227,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 160,
                "code" => "NG",
                "name" => "Nigeria",
                "phone_code" => 234,
                "currency_id" => 102,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 161,
                "code" => "NU",
                "name" => "Niue",
                "phone_code" => 683,
                "currency_id" => 100,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 162,
                "code" => "NF",
                "name" => "Norfolk Island",
                "phone_code" => 672,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 17,
            ],
            [
                "id" => 163,
                "code" => "MP",
                "name" => "Northern Mariana Islands",
                "phone_code" => 1670,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 164,
                "code" => "NO",
                "name" => "Norway",
                "phone_code" => 47,
                "currency_id" => 103,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 165,
                "code" => "OM",
                "name" => "Oman",
                "phone_code" => 968,
                "currency_id" => 104,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 166,
                "code" => "PK",
                "name" => "Pakistan",
                "phone_code" => 92,
                "currency_id" => 105,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 167,
                "code" => "PW",
                "name" => "Palau",
                "phone_code" => 680,
                "currency_id" => 4,
                "region_id" => 4,
                "subregion_id" => 19,
            ],
            [
                "id" => 168,
                "code" => "PS",
                "name" => "Palestinian Territory Occupied",
                "phone_code" => 970,
                "currency_id" => 46,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 169,
                "code" => "PA",
                "name" => "Panama",
                "phone_code" => 507,
                "currency_id" => 106,
                "region_id" => 5,
                "subregion_id" => 22,
            ],
            [
                "id" => 170,
                "code" => "PG",
                "name" => "Papua new Guinea",
                "phone_code" => 675,
                "currency_id" => 107,
                "region_id" => 4,
                "subregion_id" => 18,
            ],
            [
                "id" => 171,
                "code" => "PY",
                "name" => "Paraguay",
                "phone_code" => 595,
                "currency_id" => 108,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 172,
                "code" => "PE",
                "name" => "Peru",
                "phone_code" => 51,
                "currency_id" => 109,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 173,
                "code" => "PH",
                "name" => "Philippines",
                "phone_code" => 63,
                "currency_id" => 110,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 174,
                "code" => "PN",
                "name" => "Pitcairn Island",
                "phone_code" => 0,
                "currency_id" => 100,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 175,
                "code" => "PL",
                "name" => "Poland",
                "phone_code" => 48,
                "currency_id" => 111,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 176,
                "code" => "PT",
                "name" => "Portugal",
                "phone_code" => 351,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 177,
                "code" => "PR",
                "name" => "Puerto Rico",
                "phone_code" => 1787,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 178,
                "code" => "QA",
                "name" => "Qatar",
                "phone_code" => 974,
                "currency_id" => 112,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 179,
                "code" => "RE",
                "name" => "Reunion",
                "phone_code" => 262,
                "currency_id" => 5,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 180,
                "code" => "RO",
                "name" => "Romania",
                "phone_code" => 40,
                "currency_id" => 113,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 181,
                "code" => "RU",
                "name" => "Russia",
                "phone_code" => 70,
                "currency_id" => 114,
                "region_id" => 2,
                "subregion_id" => 7,
            ],
            [
                "id" => 182,
                "code" => "RW",
                "name" => "Rwanda",
                "phone_code" => 250,
                "currency_id" => 115,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 183,
                "code" => "SH",
                "name" => "Saint Helena",
                "phone_code" => 290,
                "currency_id" => 116,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 184,
                "code" => "KN",
                "name" => "Saint Kitts And Nevis",
                "phone_code" => 1869,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 185,
                "code" => "LC",
                "name" => "Saint Lucia",
                "phone_code" => 1758,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 186,
                "code" => "PM",
                "name" => "Saint Pierre and Miquelon",
                "phone_code" => 508,
                "currency_id" => 5,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 187,
                "code" => "VC",
                "name" => "Saint Vincent And The Grenadines",
                "phone_code" => 1784,
                "currency_id" => 7,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 188,
                "code" => "WS",
                "name" => "Samoa",
                "phone_code" => 684,
                "currency_id" => 117,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 189,
                "code" => "SM",
                "name" => "San Marino",
                "phone_code" => 378,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 190,
                "code" => "ST",
                "name" => "Sao Tome and Principe",
                "phone_code" => 239,
                "currency_id" => 118,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 191,
                "code" => "SA",
                "name" => "Saudi Arabia",
                "phone_code" => 966,
                "currency_id" => 119,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 192,
                "code" => "SN",
                "name" => "Senegal",
                "phone_code" => 221,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 193,
                "code" => "RS",
                "name" => "Serbia",
                "phone_code" => 381,
                "currency_id" => 120,
                "region_id" => 2,
                "subregion_id" => 9,
            ],
            [
                "id" => 194,
                "code" => "SC",
                "name" => "Seychelles",
                "phone_code" => 248,
                "currency_id" => 121,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 195,
                "code" => "SL",
                "name" => "Sierra Leone",
                "phone_code" => 232,
                "currency_id" => 122,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 196,
                "code" => "SG",
                "name" => "Singapore",
                "phone_code" => 65,
                "currency_id" => 123,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 197,
                "code" => "SK",
                "name" => "Slovakia",
                "phone_code" => 421,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 198,
                "code" => "SI",
                "name" => "Slovenia",
                "phone_code" => 386,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 6,
            ],
            [
                "id" => 199,
                "code" => "XG",
                "name" => "Smaller Territories of the UK",
                "phone_code" => 44,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 200,
                "code" => "SB",
                "name" => "Solomon Islands",
                "phone_code" => 677,
                "currency_id" => 124,
                "region_id" => 4,
                "subregion_id" => 18,
            ],
            [
                "id" => 201,
                "code" => "SO",
                "name" => "Somalia",
                "phone_code" => 252,
                "currency_id" => 125,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 202,
                "code" => "ZA",
                "name" => "South Africa",
                "phone_code" => 27,
                "currency_id" => 126,
                "region_id" => 3,
                "subregion_id" => 15,
            ],
            [
                "id" => 203,
                "code" => "GS",
                "name" => "South Georgia",
                "phone_code" => 0,
                "currency_id" => 127,
                "region_id" => 6,
                "subregion_id" => 1,
            ],
            [
                "id" => 204,
                "code" => "SS",
                "name" => "South Sudan",
                "phone_code" => 211,
                "currency_id" => 128,
                "region_id" => 3,
                "subregion_id" => 13,
            ],
            [
                "id" => 205,
                "code" => "ES",
                "name" => "Spain",
                "phone_code" => 34,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 206,
                "code" => "LK",
                "name" => "Sri Lanka",
                "phone_code" => 94,
                "currency_id" => 129,
                "region_id" => 1,
                "subregion_id" => 4,
            ],
            [
                "id" => 207,
                "code" => "SD",
                "name" => "Sudan",
                "phone_code" => 249,
                "currency_id" => 130,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 208,
                "code" => "SR",
                "name" => "Suriname",
                "phone_code" => 597,
                "currency_id" => 131,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 209,
                "code" => "SJ",
                "name" => "Svalbard And Jan Mayen Islands",
                "phone_code" => 47,
                "currency_id" => 103,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 210,
                "code" => "SZ",
                "name" => "Swaziland",
                "phone_code" => 268,
                "currency_id" => 132,
                "region_id" => 3,
                "subregion_id" => 15,
            ],
            [
                "id" => 211,
                "code" => "SE",
                "name" => "Sweden",
                "phone_code" => 46,
                "currency_id" => 133,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 212,
                "code" => "CH",
                "name" => "Switzerland",
                "phone_code" => 41,
                "currency_id" => 83,
                "region_id" => 2,
                "subregion_id" => 11,
            ],
            [
                "id" => 213,
                "code" => "SY",
                "name" => "Syria",
                "phone_code" => 963,
                "currency_id" => 134,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 214,
                "code" => "TW",
                "name" => "Taiwan",
                "phone_code" => 886,
                "currency_id" => 135,
                "region_id" => 1,
                "subregion_id" => 2,
            ],
            [
                "id" => 215,
                "code" => "TJ",
                "name" => "Tajikistan",
                "phone_code" => 992,
                "currency_id" => 136,
                "region_id" => 1,
                "subregion_id" => 1,
            ],
            [
                "id" => 216,
                "code" => "TZ",
                "name" => "Tanzania",
                "phone_code" => 255,
                "currency_id" => 137,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 217,
                "code" => "TH",
                "name" => "Thailand",
                "phone_code" => 66,
                "currency_id" => 138,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 218,
                "code" => "TG",
                "name" => "Togo",
                "phone_code" => 228,
                "currency_id" => 19,
                "region_id" => 3,
                "subregion_id" => 16,
            ],
            [
                "id" => 219,
                "code" => "TK",
                "name" => "Tokelau",
                "phone_code" => 690,
                "currency_id" => 100,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 220,
                "code" => "TO",
                "name" => "Tonga",
                "phone_code" => 676,
                "currency_id" => 139,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 221,
                "code" => "TT",
                "name" => "Trinidad And Tobago",
                "phone_code" => 1868,
                "currency_id" => 140,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 222,
                "code" => "TN",
                "name" => "Tunisia",
                "phone_code" => 216,
                "currency_id" => 141,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 223,
                "code" => "TR",
                "name" => "Turkey",
                "phone_code" => 90,
                "currency_id" => 142,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 224,
                "code" => "TM",
                "name" => "Turkmenistan",
                "phone_code" => 7370,
                "currency_id" => 143,
                "region_id" => 1,
                "subregion_id" => 1,
            ],
            [
                "id" => 225,
                "code" => "TC",
                "name" => "Turks And Caicos Islands",
                "phone_code" => 1649,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 226,
                "code" => "TV",
                "name" => "Tuvalu",
                "phone_code" => 688,
                "currency_id" => 11,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 227,
                "code" => "UG",
                "name" => "Uganda",
                "phone_code" => 256,
                "currency_id" => 144,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 228,
                "code" => "UA",
                "name" => "Ukraine",
                "phone_code" => 380,
                "currency_id" => 145,
                "region_id" => 2,
                "subregion_id" => 7,
            ],
            [
                "id" => 229,
                "code" => "AE",
                "name" => "United Arab Emirates",
                "phone_code" => 971,
                "currency_id" => 146,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 230,
                "code" => "GB",
                "name" => "United Kingdom",
                "phone_code" => 44,
                "currency_id" => 116,
                "region_id" => 2,
                "subregion_id" => 8,
            ],
            [
                "id" => 231,
                "code" => "US",
                "name" => "United States",
                "phone_code" => 1,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 232,
                "code" => "UM",
                "name" => "United States Minor Outlying Islands",
                "phone_code" => 1,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 23,
            ],
            [
                "id" => 233,
                "code" => "UY",
                "name" => "Uruguay",
                "phone_code" => 598,
                "currency_id" => 147,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 234,
                "code" => "UZ",
                "name" => "Uzbekistan",
                "phone_code" => 998,
                "currency_id" => 148,
                "region_id" => 1,
                "subregion_id" => 1,
            ],
            [
                "id" => 235,
                "code" => "VU",
                "name" => "Vanuatu",
                "phone_code" => 678,
                "currency_id" => 149,
                "region_id" => 4,
                "subregion_id" => 18,
            ],
            [
                "id" => 236,
                "code" => "VA",
                "name" => "Vatican City State (Holy See)",
                "phone_code" => 39,
                "currency_id" => 5,
                "region_id" => 2,
                "subregion_id" => 10,
            ],
            [
                "id" => 237,
                "code" => "VE",
                "name" => "Venezuela",
                "phone_code" => 58,
                "currency_id" => 150,
                "region_id" => 5,
                "subregion_id" => 24,
            ],
            [
                "id" => 238,
                "code" => "VN",
                "name" => "Vietnam",
                "phone_code" => 84,
                "currency_id" => 151,
                "region_id" => 1,
                "subregion_id" => 3,
            ],
            [
                "id" => 239,
                "code" => "VG",
                "name" => "Virgin Islands (British)",
                "phone_code" => 1284,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 240,
                "code" => "VI",
                "name" => "Virgin Islands (US)",
                "phone_code" => 1340,
                "currency_id" => 4,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 241,
                "code" => "WF",
                "name" => "Wallis And Futuna Islands",
                "phone_code" => 681,
                "currency_id" => 51,
                "region_id" => 4,
                "subregion_id" => 20,
            ],
            [
                "id" => 242,
                "code" => "EH",
                "name" => "Western Sahara",
                "phone_code" => 212,
                "currency_id" => 3,
                "region_id" => 3,
                "subregion_id" => 14,
            ],
            [
                "id" => 243,
                "code" => "YE",
                "name" => "Yemen",
                "phone_code" => 967,
                "currency_id" => 152,
                "region_id" => 1,
                "subregion_id" => 5,
            ],
            [
                "id" => 244,
                "code" => "YU",
                "name" => "Yugoslavia",
                "phone_code" => 38,
                "currency_id" => 10,
                "region_id" => 5,
                "subregion_id" => 21,
            ],
            [
                "id" => 245,
                "code" => "ZM",
                "name" => "Zambia",
                "phone_code" => 260,
                "currency_id" => 153,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
            [
                "id" => 246,
                "code" => "ZW",
                "name" => "Zimbabwe",
                "phone_code" => 263,
                "currency_id" => 24,
                "region_id" => 3,
                "subregion_id" => 12,
            ],
        ];
        DB::table('countries')->insert($countries);
        DB::statement('SELECT setval(\'countries_id_seq\', COALESCE((SELECT MAX(id) + 1 FROM countries), 1), false)');
    }
}
